### ISSUE TITLE
Add capability to read consumption data form the API

### ISSUE THREAD

**Issue by masipila** [kimmolinna/pyfingrid#3]
Let's add a capability to read the consumption data from the API.

I've only used github earlier on my personal projects where I'm the only contributor so I've never created a pull request before... Let's see how this goes.

**Comment by masipila** [comment]
Ok this is a bit embarassing... Do I first need to create a fork of this repo so that I can then create a pull request which compares the current kimmolinna/pyfingrid and my fork?

**Comment by kimmolinna** [comment]
Now I read also consumption data.
